use_frameworks!

target 'ZJLoging_Example' do
  pod 'ZJLoging', :path => '../'
  pod 'ZJNetworking', :path => '../../ZJNetworking'

  target 'ZJLoging_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
